insert into public.scholarships
(slug,title,provider,country,region,degree_levels,fields,funding_type,tuition_coverage,stipend,airfare,accommodation,health_insurance,min_gpa_percent,min_ielts,sat_required,eligible_nationalities,deadline,official_url,status,verified_at)
values
('turkiye-scholarships','Türkiye Scholarships','Government of Türkiye','Türkiye','Europe',array['Bachelor','Master','PhD'],array['All fields'],'Fully funded','Full tuition','Monthly stipend',true,true,true,70,null,false,array['ALL'],'2027-02-20','https://www.turkiyeburslari.gov.tr/','published',now()),
('stipendium-hungaricum','Stipendium Hungaricum','Government of Hungary','Hungary','Europe',array['Bachelor','Master','PhD'],array['Engineering','Computer Science','All fields'],'Fully funded','Tuition waiver','Monthly stipend',false,true,true,null,6.0,false,array['Vietnam','ALL'],null,'https://stipendiumhungaricum.hu/','published',now()),
('global-korea-scholarship','Global Korea Scholarship','Government of Korea','South Korea','Asia',array['Bachelor','Master','PhD'],array['Engineering','All fields'],'Fully funded','Full tuition','Living allowance',true,true,true,80,null,false,array['ALL'],null,'https://www.studyinkorea.go.kr/','published',now()),
('mext','MEXT Scholarship','Government of Japan','Japan','Asia',array['Bachelor','Master','PhD'],array['Engineering','All fields'],'Fully funded','Full tuition','Monthly allowance',true,false,false,null,null,false,array['ALL'],null,'https://www.studyinjapan.go.jp/','published',now()),
('romania-government','Romanian Government Scholarship','Romanian MFA','Romania','Europe',array['Bachelor','Master','PhD'],array['Engineering','All fields'],'Fully funded','Tuition coverage','Monthly scholarship',false,true,true,null,null,false,array['ALL'],null,'https://studyinromania.gov.ro/','published',now()),
('nyuad-aid','NYU Abu Dhabi Financial Aid','NYU Abu Dhabi','United Arab Emirates','Middle East',array['Bachelor'],array['Engineering','All fields'],'Fully funded','Need-based','Need-based',false,true,true,null,7.0,false,array['ALL'],null,'https://nyuad.nyu.edu/','published',now()),
('kaist-international','KAIST International Student Scholarship','KAIST','South Korea','Asia',array['Bachelor'],array['Engineering','Computer Science'],'Fully funded','Full tuition','Monthly allowance',false,false,true,null,6.5,false,array['ALL'],null,'https://www.kaist.ac.kr/','published',now()),
('edisu-piemonte','EDISU Piemonte Scholarship','EDISU Piemonte','Italy','Europe',array['Bachelor','Master','PhD'],array['All fields'],'Partial','Income-based benefits','Varies',false,true,false,null,null,false,array['ALL'],null,'https://www.edisu.piemonte.it/','published',now()),
('harvard-aid','Need-Based Financial Aid','Harvard University','United States','North America',array['Bachelor'],array['All fields'],'Fully funded','Need-based','Need-based',false,true,true,null,null,true,array['ALL'],null,'https://college.harvard.edu/financial-aid','published',now()),
('yale-aid','Need-Based Financial Aid','Yale University','United States','North America',array['Bachelor'],array['All fields'],'Fully funded','Need-based','Need-based',false,true,true,null,null,true,array['ALL'],null,'https://admissions.yale.edu/financial-aid','published',now());
