-- Replace generic synthetic listings for selected high-volume institutions
-- with current official scholarship/funding programmes.

update public.scholarships
set status='archived',
    verification_status='needs_review',
    updated_at=now()
where status='published'
  and verification_status='needs_review'
  and link_status='generic'
  and provider in (
    'EPFL',
    'KAIST',
    'Khalifa University',
    'Nanyang Technological University',
    'Imperial College London',
    'MIT',
    'Harvard University',
    'Stanford University',
    'Seoul National University',
    'Tsinghua University'
  );

insert into public.scholarships (
  slug,title,provider,country,region,degree_levels,fields,funding_type,
  tuition_coverage,stipend,airfare,accommodation,health_insurance,
  eligible_nationalities,deadline,official_url,status,verified_at,description,
  source_label,source_url,verification_status,application_cycle,deadline_notes,
  link_status,last_checked_at,final_url
) values
(
  'epfl-excellence-master-fellowships',
  'EPFL Excellence Master Fellowships',
  'EPFL','Switzerland','Europe',array['Master'],array['All fields'],'Partial',
  'CHF 10,000 per semester for up to four semesters','CHF 10,000 per semester',
  false,true,false,array['ALL'],'2026-12-15',
  'https://www.epfl.ch/education/master/master-excellence-fellowships/how-to-apply/',
  'published',now(),
  'Merit-based EPFL fellowship for outstanding Master applicants. External applicants may also receive a reserved student room.',
  'EPFL official scholarship page',
  'https://www.epfl.ch/education/master/master-excellence-fellowships/how-to-apply/',
  'verified','2027 entry',
  'External applicants: first round December 15, 2026; second round March 31, 2027.',
  'exact',now(),
  'https://www.epfl.ch/education/master/master-excellence-fellowships/how-to-apply/'
),
(
  'kaist-international-undergraduate-scholarship',
  'KAIST Scholarship for International Undergraduate Students',
  'KAIST','South Korea','Asia',array['Bachelor'],array['All fields'],'Fully funded',
  'Full tuition for eight semesters','KRW 350,000 per month',
  false,false,true,array['ALL'],'2026-10-22',
  'https://admission.kaist.ac.kr/intl-undergraduate/support/scholarships/kaist/',
  'published',now(),
  'KAIST scholarship for admitted international undergraduate students, including full tuition, monthly living support and health insurance.',
  'KAIST International Admissions',
  'https://admission.kaist.ac.kr/intl-undergraduate/support/scholarships/kaist/',
  'verified','2027 entry',
  'Early/Spring application deadline October 22, 2026; regular Fall deadline January 14, 2027.',
  'exact',now(),
  'https://admission.kaist.ac.kr/intl-undergraduate/support/scholarships/kaist/'
),
(
  'kaist-international-graduate-scholarship',
  'KAIST Scholarship for International Graduate Students',
  'KAIST','South Korea','Asia',array['Master','PhD'],array['All fields'],'Fully funded',
  'Full tuition','Monthly stipend; amount depends on programme and scholarship type',
  false,false,true,array['ALL'],null,
  'https://admission.kaist.ac.kr/intl-graduate/FinancialSupport/Scholarship/KAISTScholarship/',
  'published',now(),
  'KAIST scholarship for international graduate students. KAIST states that the scholarship covers full tuition and provides stipends for most international students.',
  'KAIST International Graduate Admissions',
  'https://admission.kaist.ac.kr/intl-graduate/FinancialSupport/Scholarship/KAISTScholarship/',
  'verified','2027 entry',
  'Fall 2027 application dates are to be announced by KAIST.',
  'exact',now(),
  'https://admission.kaist.ac.kr/intl-graduate/FinancialSupport/Scholarship/KAISTScholarship/'
),
(
  'khalifa-undergraduate-international-scholarships',
  'Khalifa University Undergraduate Scholarships for International Students',
  'Khalifa University','United Arab Emirates','Middle East',array['Bachelor'],array['All fields'],'Varies',
  'Tiered tuition support from 25% to 100%','No standard stipend listed',
  false,false,false,array['ALL'],null,
  'https://www.ku.ac.ae/undergraduate-scholarships',
  'published',now(),
  'International undergraduate applicants are automatically assessed for tiered Khalifa University scholarship support as part of admission.',
  'Khalifa University official scholarship page',
  'https://www.ku.ac.ae/undergraduate-scholarships',
  'verified','Next available intake',
  'Current next-cycle undergraduate deadline is not yet published on the scholarship page.',
  'exact',now(),
  'https://www.ku.ac.ae/undergraduate-scholarships'
),
(
  'khalifa-graduate-scholarship-international',
  'Khalifa University Graduate Scholarship for International Students',
  'Khalifa University','United Arab Emirates','Middle East',array['Master','PhD'],array['All fields'],'Varies',
  'Tiered support up to full tuition','Stipends vary by degree and scholarship tier',
  true,true,true,array['ALL'],'2026-09-28',
  'https://www.ku.ac.ae/scholarship/graduate-research-teaching-scholarship-for-international-students',
  'published',now(),
  'Graduate scholarship for international students with tiered tuition, stipend and additional benefits depending on programme and award level.',
  'Khalifa University official scholarship page',
  'https://www.ku.ac.ae/scholarship/graduate-research-teaching-scholarship-for-international-students',
  'verified','Spring 2027 PhD',
  'Khalifa University lists September 28, 2026 as the Spring 2027 PhD admission deadline; scholarship consideration is part of admission.',
  'exact',now(),
  'https://www.ku.ac.ae/scholarship/graduate-research-teaching-scholarship-for-international-students'
),
(
  'ntu-nanyang-global-scholarship',
  'Nanyang Global Scholarship',
  'Nanyang Technological University','Singapore','Asia',array['Bachelor'],array['All fields'],'Fully funded',
  'Full subsidised tuition fees','S$6,500 living allowance per academic year',
  false,true,false,array['ALL'],null,
  'https://www.ntu.edu.sg/admissions/undergraduate/scholarships/scholarship-opportunities/detail/nanyang-scholarship',
  'published',now(),
  'NTU undergraduate scholarship open to all nationalities, with tuition coverage, living allowance, accommodation support, travel grant and computer allowance.',
  'NTU Singapore official scholarship page',
  'https://www.ntu.edu.sg/admissions/undergraduate/scholarships/scholarship-opportunities/detail/nanyang-scholarship',
  'verified','AY2027/28',
  'Scholarship application period follows the undergraduate admission period; closing date depends on applicant qualification.',
  'exact',now(),
  'https://www.ntu.edu.sg/admissions/undergraduate/scholarships/scholarship-opportunities/detail/nanyang-scholarship'
),
(
  'ntu-research-scholarship',
  'NTU Research Scholarship',
  'Nanyang Technological University','Singapore','Asia',array['Master','PhD'],array['All fields'],'Fully funded',
  'Annual tuition fee','Monthly stipend for eligible research students',
  false,false,false,array['ALL'],'2027-01-31',
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/rss',
  'published',now(),
  'Research scholarship open to local and international full-time graduate research students. Application timing varies by school and programme.',
  'NTU Singapore official scholarship page',
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/rss',
  'verified','August 2027 intake',
  'Some programmes, including Nanyang Business School, list January 31, 2027 for the August 2027 intake.',
  'exact',now(),
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/rss'
),
(
  'ntu-nanyang-presidents-graduate-scholarship',
  'Nanyang President''s Graduate Scholarship',
  'Nanyang Technological University','Singapore','Asia',array['PhD'],array['All fields'],'Fully funded',
  'Annual tuition fee','S$4,300 monthly stipend for international students (2026 rate)',
  false,true,false,array['ALL'],null,
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/npgs',
  'published',now(),
  'Prestigious NTU scholarship for outstanding PhD candidates of all nationalities, with tuition and a monthly stipend.',
  'NTU Singapore official scholarship page',
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/npgs',
  'verified','AY2027/28',
  'NTU states that the AY2027/28 application period will be announced in due course.',
  'exact',now(),
  'https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships/npgs'
),
(
  'imperial-presidents-phd-scholarships-2027',
  'Imperial President''s PhD Scholarships',
  'Imperial College London','United Kingdom','Europe',array['PhD'],array['All fields'],'Fully funded',
  'Full tuition fees','GBP 27,036 per year stipend for 2027/28',
  false,false,false,array['ALL'],'2026-11-02',
  'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/',
  'published',now(),
  'Fifty fully funded PhD scholarships for high-performing candidates from the UK and worldwide.',
  'Imperial College London official scholarship page',
  'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/',
  'verified','2027/28',
  'Application rounds: November 2, 2026; January 11, 2027; March 1, 2027.',
  'exact',now(),
  'https://www.imperial.ac.uk/study/fees-and-funding/postgraduate-doctoral/grants-scholarships/presidents-phd/'
),
(
  'imperial-inspires-scholarships-2027',
  'Imperial Inspires Scholarships',
  'Imperial College London','United Kingdom','Europe',array['Bachelor','Master'],array['All fields'],'Partial',
  'GBP 15,000 per year','GBP 15,000 per year',
  false,false,false,array['ALL'],null,
  'https://www.imperial.ac.uk/study/fees-and-funding/imperial-inspires-scholarships/',
  'published',now(),
  'At least 300 scholarships for international students entering eligible undergraduate and selected postgraduate taught courses in 2027.',
  'Imperial College London official scholarship page',
  'https://www.imperial.ac.uk/study/fees-and-funding/imperial-inspires-scholarships/',
  'verified','2027/28',
  'Applications open with 2027 course applications; Imperial has not yet published a scholarship closing date.',
  'exact',now(),
  'https://www.imperial.ac.uk/study/fees-and-funding/imperial-inspires-scholarships/'
),
(
  'mit-international-undergraduate-financial-aid',
  'MIT Need-Based Financial Aid for International Undergraduates',
  'Massachusetts Institute of Technology','United States','North America',array['Bachelor'],array['All fields'],'Fully funded',
  'Meets 100% of demonstrated financial need','Need-based grant aid; amount varies',
  false,false,false,array['ALL'],'2026-11-30',
  'https://sfs.mit.edu/undergraduate-students/apply-for-aid/international/',
  'published',now(),
  'MIT meets 100% of demonstrated financial need for admitted international undergraduates using the same aid process as domestic applicants.',
  'MIT Student Financial Services',
  'https://sfs.mit.edu/undergraduate-students/apply-for-aid/international/',
  'verified','2027 entry',
  'Financial aid deadlines: November 30 for Early Action and February 15 for Regular Action.',
  'exact',now(),
  'https://sfs.mit.edu/undergraduate-students/apply-for-aid/international/'
),
(
  'harvard-international-undergraduate-financial-aid',
  'Harvard College Need-Based Financial Aid for International Students',
  'Harvard University','United States','North America',array['Bachelor'],array['All fields'],'Fully funded',
  'Meets 100% of demonstrated financial need','Need-based grant aid; amount varies',
  false,false,false,array['ALL'],'2026-11-01',
  'https://college.harvard.edu/financial-aid/apply-financial-aid/prospective-students',
  'published',now(),
  'Harvard states that international students are eligible for the same need-based aid as U.S. students.',
  'Harvard College official financial aid page',
  'https://college.harvard.edu/financial-aid/apply-financial-aid/prospective-students',
  'verified','2027 entry',
  'Financial aid deadlines: November 1 for Restrictive Early Action and February 1 for Regular Decision.',
  'exact',now(),
  'https://college.harvard.edu/financial-aid/apply-financial-aid/prospective-students'
)
on conflict (slug) do update set
  title=excluded.title,
  provider=excluded.provider,
  country=excluded.country,
  region=excluded.region,
  degree_levels=excluded.degree_levels,
  fields=excluded.fields,
  funding_type=excluded.funding_type,
  tuition_coverage=excluded.tuition_coverage,
  stipend=excluded.stipend,
  airfare=excluded.airfare,
  accommodation=excluded.accommodation,
  health_insurance=excluded.health_insurance,
  eligible_nationalities=excluded.eligible_nationalities,
  deadline=excluded.deadline,
  official_url=excluded.official_url,
  status=excluded.status,
  verified_at=excluded.verified_at,
  description=excluded.description,
  source_label=excluded.source_label,
  source_url=excluded.source_url,
  verification_status=excluded.verification_status,
  application_cycle=excluded.application_cycle,
  deadline_notes=excluded.deadline_notes,
  link_status=excluded.link_status,
  last_checked_at=excluded.last_checked_at,
  final_url=excluded.final_url,
  updated_at=now();
