-- App Store UGC safety: server-enforced objectionable-content filtering.
-- Keep the blocklist in the database so it can be expanded without an app release.

create table if not exists public.content_moderation_patterns (
  id bigint generated by default as identity primary key,
  pattern text not null unique,
  category text not null default 'objectionable',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.content_moderation_patterns enable row level security;
revoke all on public.content_moderation_patterns
from public, anon, authenticated;

insert into public.content_moderation_patterns(pattern, category)
values
  ('\\b(?:fuck|fucking|motherfucker)\\b', 'profanity'),
  ('\\b(?:nigger|kike|faggot)\\b', 'hate'),
  ('\\b(?:kill yourself|kys)\\b', 'self_harm_abuse'),
  ('\\b(?:rape you|i will rape)\\b', 'sexual_threat'),
  ('\\b(?:i will kill you|going to kill you)\\b', 'violent_threat'),
  ('\\b(?:child porn|child pornography)\\b', 'sexual_exploitation'),
  ('(?:пош[её]л нах|иди нах|сука бля)', 'profanity'),
  ('(?:địt mẹ|đụ má)', 'profanity')
on conflict (pattern) do nothing;

create or replace function public.user_content_is_allowed(
  p_content text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1
    from public.content_moderation_patterns p
    where p.active
      and coalesce(p_content, '') ~* p.pattern
  );
$$;

revoke execute on function public.user_content_is_allowed(text)
from public, anon;
grant execute on function public.user_content_is_allowed(text)
to authenticated;

create or replace function public.enforce_user_content_moderation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text := '';
begin
  if current_user in ('postgres', 'service_role', 'supabase_admin')
     or coalesce(auth.role(), '') = 'service_role'
     or public.is_admin() then
    return new;
  end if;

  if tg_table_name = 'messages' then
    candidate := new.body;
  elsif tg_table_name = 'social_posts' then
    candidate := new.caption;
  elsif tg_table_name = 'social_post_comments' then
    candidate := new.body;
  elsif tg_table_name = 'community_profiles' then
    candidate := concat_ws(' ', new.display_name, new.bio);
  else
    return new;
  end if;

  if not public.user_content_is_allowed(candidate) then
    raise exception 'Content blocked by the community safety filter'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists messages_content_moderation
on public.messages;
create trigger messages_content_moderation
before insert or update on public.messages
for each row
execute function public.enforce_user_content_moderation();

drop trigger if exists social_posts_content_moderation
on public.social_posts;
create trigger social_posts_content_moderation
before insert or update on public.social_posts
for each row
execute function public.enforce_user_content_moderation();

drop trigger if exists social_comments_content_moderation
on public.social_post_comments;
create trigger social_comments_content_moderation
before insert or update on public.social_post_comments
for each row
execute function public.enforce_user_content_moderation();

drop trigger if exists community_profiles_content_moderation
on public.community_profiles;
create trigger community_profiles_content_moderation
before insert or update on public.community_profiles
for each row
execute function public.enforce_user_content_moderation();
